spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:member;MODE=MYSQL;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        metadata_builder_contributor: me.jaeyeon.blog.config.SqlFunctionsMetadataBuilderContributor
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/blog"
    username: ${SPRING_DATABASE_NAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        metadata_builder_contributor: me.jaeyeon.blog.config.SqlFunctionsMetadataBuilderContributor
        dialect: org.hibernate.dialect.MySQL8Dialect
