name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: './readit-api/src/main/resources/application.yml'
        env:
          override.value: ${{ secrets.APPLICATION }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean :readit-api:buildNeeded --stacktrace --info -x test
        shell: bash
