name: CI/CD with Spring Boot

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - "src/**"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@v0.7.5
        with:
          checkstyle_config: ${{ github.workspace }}/config/checkstyle/naver-checkstyle-rules.xml
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make application.yml
        run: |
          cd ./readit-api/src/main
          mkdir -p resources
          cd ./resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
        shell: bash

        env:
          override.value: ${{ secrets.APPLICATION }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean :readit-api:buildNeeded --stacktrace --info -x test
        shell: bash

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/customJacocoReportDir/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
